### ISSUE TITLE
Cancel or Update an event

### ISSUE THREAD

**Issue by vdellangela-kindred** [spatie/calendar-links#21]
Hey, 

First I'd like to say thank you for all the plugins you developed! It helps a lot :)

In regards to this calendar-links plugin, would it be possible to update the plugin and add a new feature to cancel/update an event? 

I looked at the iCalendar documentation and found an attribute called "STATUS" that is optional and is used to indicate if the event has been cancelled for instance.

Would you be able to add it to your plugin by any chance?

Thanks a lot!

**Comment by Eyalevin** [comment]
Hii @vdellangela-kindred ,
First of all, thank you for your contribution to the project.

The project generated URL to add an event to the calendar manual 
as an event without participants so the STATUS Irrelevant

*If I understood wrong I would be happy if you corrected me

**Comment by vdellangela-kindred** [comment]
Sorry I'm not sure I understood what you said.

I would be looking for a way to cancel an event using your links (ics, google, yahoo) that I would put in a custom email.
Would you have any idea how to do it?

**Comment by Eyalevin** [comment]
@vdellangela-kindred 
In the configuration, this project is not possible
Adding the event is done directly to the calendar without invitees, in order to do what you want it is necessary to send an invitation to each guest is possible only by integrating the calendar of one of the managers (which is the event manager)
