### ISSUE TITLE
Version 1.2.3 is missing the fix of Yahoo Generator broken #35

### ISSUE THREAD

**Issue by samirchauhan** [spatie/calendar-links#68]
The fix is already there in 1.2.1 but is missing from 1.2.2 and 1.2.3 and also from the master branch. Will there be an issue if I use the code from 1.2.1 in my project. @lptn 

#35

**Comment by lptn** [comment]
Hey @samirchauhan 
Thanks for the report. Unfortunately, there is nothing with regard to Yahoo in 1.2.3 release: https://github.com/spatie/calendar-links/compare/1.2.2...1.2.3

Did you probably mean other release, like 1.2.2 https://github.com/spatie/calendar-links/compare/1.2.1...1.2.2  or https://github.com/spatie/calendar-links/compare/1.2.0...1.2.1 ?

Could you please describe how to reproduce the issue?

**Comment by samirchauhan** [comment]
Hey @
` if ($link->allDay) {
            $dateTimeFormat = 'Ymd';
            $url .= '&st='.$link->from->format($dateTimeFormat);
            $url .= '&dur=allday';
        } else {
            $utcStartDateTime = (clone $link->from)->setTimezone(new DateTimeZone('UTC'));
            $utcEndDateTime = (clone $link->to)->setTimezone(new DateTimeZone('UTC'));
            $dateTimeFormat = $link->allDay ? 'Ymd' : 'Ymd\THis';
            $url .= '&st='.$utcStartDateTime->format($dateTimeFormat).'Z';
            $url .= '&dur='.date_diff($utcStartDateTime, $utcEndDateTime)->format('%H%I');
        }`

I am mentioning about this code which is in 1.2.1 branch and missing from master branch. This code fixes the incorrect time in Yahoo calendar as Yahoo doesn't play nice with end date instead use the duration attribute.

**Comment by lptn** [comment]
@samirchauhan 
Sorry, I couldn't understand what's wrong with Yahoo's `et` (end time) parameter. Could you please elaborate? Please also check an example from our tests, that works fine on yahoo calendar:  https://calendar.yahoo.com/?v=60&view=d&type=20&title=Birthday&st=20180201T090000Z&et=20180201T180000Z&desc=With%20balloons%2C%20clowns%20and%20stuff%0ABring%20a%20dog%2C%20bring%20a%20frog&in_loc=Party%20Lane%201A%2C%201337%20Funtown&guccounter=1

![image](https://user-images.githubusercontent.com/5278175/61365155-e195ee80-a88f-11e9-9862-d6e2dc34eaff.png)

In this example we used:
 - st=20180201T090000Z
 - et=20180201T180000Z

**Comment by samirchauhan** [comment]
Hi @lptn ,

Please find below links and dates in different calendars:
1. Google Calendar:
https://calendar.google.com/calendar/r/eventedit?text=TM:+The+Operationalisation+of+CPS+234++-+Sydney&dates=20190801T160000Z/20190801T190000Z&ctz=UTC&details=TM:+The+Operationalisation+of+CPS+234++-+Sydney&location=Le+Petit+Flot+Restaurant+and+Wine+Bar+-+The+Tank+Stream+Hotel,+97+Pitt+St,+Sydney+NSW+2000,+Australia&sprop&sprop=name:&t=AKUaPmYU2BOccBwiDdL9KpJKvzH_BTZ_OuxKf5-tGtYSwJ0_dgXXjPyFalTQWkY5IOjH5MV7APU5D1_ECHFtcwcD9bavV5OFWw%3D%3D

![google_calendar](https://user-images.githubusercontent.com/10740850/61373071-701d6680-a8b6-11e9-9372-9fb5fb4b5c10.png)
2. Web Outlook:
https://outlook.live.com/owa/?path=/calendar/action/compose&rru=addevent&startdt=20190801T160000&enddt=20190801T190000&subject=UTM%3A+The+Operationalisation+of+CPS+234++-+Sydney&body=TM%3A+The+Operationalisation+of+CPS+234++-+Sydney&location=Le+Petit+Flot+Restaurant+and+Wine+Bar+-+The+Tank+Stream+Hotel%2C+97+Pitt+St%2C+Sydney+NSW+2000%2C+Australia

![weboutlook](https://user-images.githubusercontent.com/10740850/61373118-917e5280-a8b6-11e9-9255-855d6af2746b.png)

3. Yahoo Calendar:
https://calendar.yahoo.com/?v=60&view=d&type=20&title=The+Operationalisation+of+CPS+234++-+Sydney&st=20190801T160000Z&et=20190801T190000Z&desc=The+Operationalisation+of+CPS+234++-+Sydney&in_loc=Le+Petit+Flot+Restaurant+and+Wine+Bar+-+The+Tank+Stream+Hotel%2C+97+Pitt+St%2C+Sydney+NSW+2000%2C+Australia

![yahoo_calendar](https://user-images.githubusercontent.com/10740850/61373143-a3f88c00-a8b6-11e9-842d-934956101275.png)

**Comment by lptn** [comment]
@samirchauhan 
Thanks, I got it! I'll take a look soon and fix the problem.

**Comment by samirchauhan** [comment]
@lptn ,

I fixed the issue using dur attribute instead of end date and is working pretty well so that's why wondering why was that code missing from the master branch.

**Comment by OksanaRomaniv** [comment]
The issue is still there for me on version 1.2.4

**Comment by samirchauhan** [comment]
Hi @OksanaRomaniv,

Please use the Yahoo Generator code from branch 1.2.1. I used the same code and is working fine for me. Showing correct start and end time for the event.
 Here's the link to branch: 

https://github.com/spatie/calendar-links/blob/1.2.1/src/Generators/Yahoo.php

**Comment by OksanaRomaniv** [comment]
Hello @samirchauhan ,

Thank you for suggestion. I've tried it with my events manager, but it didn't pull the correct date. The timezone and the times are looking right, but the day is set the same, though the event is going to span 3 days. Any ideas why?

Thanks!

**Comment by wykananda** [comment]
Hello @samirchauhan and @lptn ,

As @OksanaRomaniv mentioned,  the Yahoo Generator code in branch 1.2.1 won't work properly for start and end dates that aren't the same day.  The &dur parameter needs to represent the _cumulative_ hours and minutes difference between dates.

To fix that, replace this line from branch 1.2.1:
```php
$url .= '&dur='.date_diff($utcStartDateTime, $utcEndDateTime)->format('%H%I');
```

with this:
```php
$interval= $utcStartDateTime->diff($utcEndDateTime);
$url .= '&dur='.sprintf("%04d", min( ((($interval->days * 24) + $interval->h) * 100 ) + $interval->i, 9959));
```

Note that the maximum duration yahoo can except is 99 hours and 59 minutes due to the limitation of the format (ie. hhmm).  The code above accounts for that.

Here's the whole function. It'd be great if you can include this fix in your next release:

```php
public function generate(Link $link): string 
{
        $url = 'https://calendar.yahoo.com/?v=60&view=d&type=20';

        $url .= '&title='.urlencode($link->title);

        if ($link->allDay) {
            $dateTimeFormat = 'Ymd';
            $url .= '&st='.$link->from->format($dateTimeFormat);
            $url .= '&dur=allday';
        } else {
            $dateTimeFormat = 'Ymd\THis';
            $utcStartDateTime = (clone $link->from)->setTimezone(new DateTimeZone('UTC'));
            $utcEndDateTime = (clone $link->to)->setTimezone(new DateTimeZone('UTC'));

            $url .= '&st='.$utcStartDateTime->format($dateTimeFormat).'Z';

            $interval= $utcStartDateTime->diff($utcEndDateTime);
            $url .= '&dur='.sprintf("%04d", min( ((($interval->days * 24) + $interval->h) * 100 ) + $interval->i, 9959));
        }

        if ($link->description) {
            $url .= '&desc='.urlencode($link->description);
        }

        if ($link->address) {
            $url .= '&in_loc='.urlencode($link->address);
        }

        return $url;
    }
```

**Comment by lptn** [comment]
@wykananda 
@OksanaRomaniv
As @wykananda  mentioned, `dur` parameter has a limitation, that's why it's preferable to use end date.

I also did some tests and found that Yahoo converts start date to current user's tz, but doesn't do the same for end date:
UTC (this package generates this version)
https://calendar.yahoo.com/?v=60&view=d&type=20&st=20191230T230000Z&et=20200102T010000Z&title=New+Year+from+2019-12-30-23:00:00-UTC+to+2020-01-02+01:00:00-UTC&desc=With+balloons%2C+clowns+and+stuff%0ABring+a+dog%2C+bring+a+frog&in_loc=Party+Lane+1A%2C+1337+Funtown


Link with current user's timezone (timezone omitted in both dates)
https://calendar.yahoo.com/?v=60&view=d&type=20&st=20191230T230000&et=20200102T010000&title=New+Year+from+2019-12-30-23:00:00+to+2020-01-02+01:00:00&desc=With+balloons%2C+clowns+and+stuff%0ABring+a+dog%2C+bring+a+frog&in_loc=Party+Lane+1A%2C+1337+Funtown

This is how yahoo process start date (``):
```js
f.startTime = new Date(q[1] * 1, q[2] - 1, q[3] * 1, q[4] * 1, q[5] * 1, q[6] * 1);
if (Config.args.st.indexOf("Z") != -1) {
    f.startTime.setTimezone("UTC");
}
```

and this is how end date (`st`):
```js
q = k.exec(Config.args[E]);
if (q === null) {
    q = B.exec(Config.args[E]);
    q = q.concat([0, 0, 0]);
}
f.endTime = new Date(q[1] * 1, q[2] - 1, q[3] * 1, q[4] * 1, q[5] * 1, q[6] * 1);
```
you see, they don't process timezone at all

We should probably combine dur and et: use `dur` for durations less or eq. to max duration (99 h and 59mins) and use `et` for longer durations as more accurate (but still buggy) option.

**Comment by lptn** [comment]
fixed
